import * as fs from "fs";
import * as path from "path";
import * as yaml from "js-yaml";
import type { DetectedStack } from "./detect";
import { generateDockerfile, generateDockerignore } from "./templates";

interface ComposeServiceDef {
  build?: string;
  image?: string;
  ports?: string[];
  environment?: Record<string, string>;
  depends_on?: string[];
}

export function generateComposeFromStack(
  stack: DetectedStack,
  projectDir: string
): string {
  const services: Record<string, ComposeServiceDef> = {};

  // Build environment variables for the app service
  const appEnv: Record<string, string> = {};
  const dependsOn: string[] = [];

  for (const db of stack.databases) {
    switch (db.type) {
      case "postgres":
        appEnv.DATABASE_URL = `postgres://postgres:cloudenv@db:5432/app`;
        dependsOn.push("db");
        break;
      case "redis":
        appEnv.REDIS_URL = `redis://redis:6379`;
        dependsOn.push("redis");
        break;
      case "mongo":
        appEnv.MONGODB_URI = `mongodb://mongo:27017/app`;
        dependsOn.push("mongo");
        break;
      case "mysql":
        appEnv.DATABASE_URL = `mysql://root:cloudenv@mysql:3306/app`;
        dependsOn.push("mysql");
        break;
    }
  }

  // App service
  const appService: ComposeServiceDef = {
    build: ".",
    ports: [`${stack.port}:${stack.port}`],
  };
  if (Object.keys(appEnv).length > 0) {
    appService.environment = appEnv;
  }
  if (dependsOn.length > 0) {
    appService.depends_on = dependsOn;
  }
  services.app = appService;

  // Database services
  for (const db of stack.databases) {
    const serviceName = db.type === "postgres" ? "db" : db.type;
    const svc: ComposeServiceDef = { image: db.image };
    if (Object.keys(db.envVars).length > 0) {
      svc.environment = db.envVars;
    }
    services[serviceName] = svc;
  }

  const composeDoc = { services };
  const header = "# Generated by cloudenv auto-detection\n# Edit this file to customize your environment\n";
  return header + yaml.dump(composeDoc, { lineWidth: -1, noRefs: true });
}

export function writeGeneratedFiles(
  stack: DetectedStack,
  projectDir: string
): { composePath: string; dockerfilePath?: string; dockerignorePath?: string } {
  const result: { composePath: string; dockerfilePath?: string; dockerignorePath?: string } = {
    composePath: path.join(projectDir, "docker-compose.cloudenv.yml"),
  };

  // Write compose file
  const composeContent = generateComposeFromStack(stack, projectDir);
  fs.writeFileSync(result.composePath, composeContent);

  // Write Dockerfile if project doesn't have one
  if (!stack.hasDockerfile) {
    const dockerfileContent = generateDockerfile(stack);
    result.dockerfilePath = path.join(projectDir, "Dockerfile");
    fs.writeFileSync(result.dockerfilePath, dockerfileContent);
  }

  // Write .dockerignore if one doesn't exist
  const dockerignorePath = path.join(projectDir, ".dockerignore");
  if (!fs.existsSync(dockerignorePath)) {
    fs.writeFileSync(dockerignorePath, generateDockerignore());
    result.dockerignorePath = dockerignorePath;
  }

  return result;
}
