import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { generateComposeFromStack, writeGeneratedFiles } from "../generate-compose";
import type { DetectedStack } from "../detect";

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "cloudenv-gen-"));
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

const baseStack: DetectedStack = {
  runtime: "node",
  version: "20",
  entrypoint: "npm start",
  port: 3000,
  databases: [],
  hasDockerfile: false,
};

describe("generateComposeFromStack", () => {
  it("generates single-service compose for app-only project", () => {
    const result = generateComposeFromStack(baseStack, tmpDir);
    expect(result).toContain("services:");
    expect(result).toContain("app:");
    expect(result).toContain("build: .");
    expect(result).toContain("3000:3000");
    expect(result).not.toContain("db:");
  });

  it("adds postgres service when detected", () => {
    const stack: DetectedStack = {
      ...baseStack,
      databases: [{ type: "postgres", image: "postgres:16-alpine", port: 5432, envVars: { POSTGRES_PASSWORD: "cloudenv", POSTGRES_DB: "app" } }],
    };
    const result = generateComposeFromStack(stack, tmpDir);
    expect(result).toContain("db:");
    expect(result).toContain("postgres:16-alpine");
    expect(result).toContain("DATABASE_URL");
    expect(result).toContain("depends_on:");
  });

  it("adds redis service when detected", () => {
    const stack: DetectedStack = {
      ...baseStack,
      databases: [{ type: "redis", image: "redis:7-alpine", port: 6379, envVars: {} }],
    };
    const result = generateComposeFromStack(stack, tmpDir);
    expect(result).toContain("redis:");
    expect(result).toContain("redis:7-alpine");
    expect(result).toContain("REDIS_URL");
  });

  it("includes generated-by header", () => {
    const result = generateComposeFromStack(baseStack, tmpDir);
    expect(result).toContain("Generated by cloudenv");
  });
});

describe("writeGeneratedFiles", () => {
  it("writes compose file to disk", () => {
    writeGeneratedFiles(baseStack, tmpDir);
    const composePath = path.join(tmpDir, "docker-compose.cloudenv.yml");
    expect(fs.existsSync(composePath)).toBe(true);
    const content = fs.readFileSync(composePath, "utf-8");
    expect(content).toContain("services:");
  });

  it("writes Dockerfile when project has none", () => {
    const result = writeGeneratedFiles(baseStack, tmpDir);
    expect(result.dockerfilePath).toBeDefined();
    expect(fs.existsSync(result.dockerfilePath!)).toBe(true);
    const content = fs.readFileSync(result.dockerfilePath!, "utf-8");
    expect(content).toContain("FROM node:20-alpine");
  });

  it("does not overwrite existing Dockerfile", () => {
    fs.writeFileSync(path.join(tmpDir, "Dockerfile"), "FROM custom:image");
    const stack: DetectedStack = { ...baseStack, hasDockerfile: true };
    const result = writeGeneratedFiles(stack, tmpDir);
    expect(result.dockerfilePath).toBeUndefined();
    expect(fs.readFileSync(path.join(tmpDir, "Dockerfile"), "utf-8")).toBe("FROM custom:image");
  });

  it("writes .dockerignore when none exists", () => {
    const result = writeGeneratedFiles(baseStack, tmpDir);
    expect(result.dockerignorePath).toBeDefined();
    const content = fs.readFileSync(result.dockerignorePath!, "utf-8");
    expect(content).toContain("node_modules");
    expect(content).toContain(".git");
  });

  it("does not overwrite existing .dockerignore", () => {
    fs.writeFileSync(path.join(tmpDir, ".dockerignore"), "custom");
    const result = writeGeneratedFiles(baseStack, tmpDir);
    expect(result.dockerignorePath).toBeUndefined();
  });
});
